### ISSUE TITLE
Why you dont get data from API actions?

### ISSUE THREAD

**Issue by feedgit** [srhise/nuxt-wordpress-pwa#4]
I see this file you get API directly: https://github.com/srhise/nuxt-wordpress-pwa/blob/master/pages/_slug/index.vue but in API file you have an action to get data for Single Post from API: https://github.com/srhise/nuxt-wordpress-pwa/blob/master/api/index.js
Why you dont get data from API actions?

**Comment by srhise** [comment]
Because I was having issues with it. The asycData works so you get the API call before page render, thus SSR'ing the whole page's content. It an be improved.

**Comment by congtoanle** [comment]
Hope it for next Push. Thank you!
