### ISSUE TITLE
Info regards this modus operandi

### ISSUE THREAD

**Issue by mcpll** [srhise/nuxt-wordpress-pwa#5]
Hi, I can not understand if this stack you create can update content directly from the wp admin panel.

Or you need to upgrade the content in two steps.

1 Enter the wp admin panel, modify the saved content.

2 Npm throws generated to recreate all site pages that have been developed with nuxt.

**Comment by srhise** [comment]
Nope, it's completely dynamic. It looks up the post content by it's slug, so it's a dynamic route. It does not require anything special to regenerate the site.
